name: Manual

on:
  workflow_dispatch:
    inputs:
      deployment-environment:
        required: true
        type: string
        options:
          - 'dev'
          - 'stg'
          - 'prd'
        description: 'Target environment'
      docker-tag:
        required: false
        type: string
        description: 'Docker tag to label the released image'
        options:
          - 'latest'
          - 'next'
    secrets:
      QUAY_USERNAME:
        required: true
      QUAY_TOKEN:
        required: true
    # outputs:
    #   registry-path:
    #     description: "Registry path"
    #     value: ${{ needs.quay-build-push.registry-path }}
    #   registry-paths:
    #     description: "Registry paths (JSON)"
    #     value: ${{ needs.quay-build-push.registry-paths }}

jobs:
  pr:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-manual-release.yml@feat/manual
    with:
      service-name: third-party-providers-resolver
      dockerfile-url: https://raw.githubusercontent.com/decentraland/platform-actions/main/Dockerfile.alpine
      docker-tag: ${{ inputs.docker-tag }}
      deployment-environment: ${{ inputs.deployment-environment }}
    secrets: inherit
