name: Manual

on:
  workflow_dispatch:
    inputs:
      service-name:
        required: true
        type: string
        description: 'Service name to deploy'
      deployment-environment:
        required: true
        type: string
        options:
          - 'dev'
          - 'stg'
          - 'prd'
        description: 'Target environment'
      docker-tag:
        required: false
        type: string
        description: 'Docker tag to label the released image'
        options:
          - 'latest'
          - 'next'
      build-args:
        required: false
        type: string
        description: 'Any arguments needed to build the docker image'
      layers:
        required: false
        type: boolean
        default: true
        description: 'Indicates if the Docker layers cache mechanism should be used. Default value: true'
      dockerfile-url:
        required: false
        type: string
        description: 'Place the URL from where the Dockerfile should be downloaded'
    secrets:
      QUAY_USERNAME:
        required: true
      QUAY_TOKEN:
        required: true
    outputs:
      registry-path:
        description: "Registry path"
        value: ${{ needs.quay-build-push.registry-path }}
      registry-paths:
        description: "Registry paths (JSON)"
        value: ${{ needs.quay-build-push.registry-paths }}

jobs:
  quay-build-push:
    runs-on: ubuntu-latest
    outputs:
      registry-path: ${{ steps.push-to-quay.outputs.registry-path }}
      registry-paths: ${{ steps.push-to-quay.outputs.registry-paths }}
    steps:
      - uses: actions/checkout@v3
      - name: download Dockerfile
        if: ${{ inputs.dockerfile-url }}
        run: wget -O Dockerfile ${{ inputs.dockerfile-url }}
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ inputs.service-name }}
          layers: ${{ inputs.layers }}
          tags: ${{ github.sha }} ${{ github.ref_name }} ${{ inputs.docker-tag }}
          dockerfiles: |
            ./Dockerfile
          build-args: |
            ${{ inputs.build-args }}
            CURRENT_VERSION=${{ github.ref_name }}
            COMMIT_HASH=${{ github.sha }}
      # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
      # in which case 'username' and 'password' can be omitted.
      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/decentraland
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

  deployment:
    if: ${{ inputs.deployment-environment }}
    needs: [quay-build-push]
    name: "Deploy to: ${{ inputs.deployment-environment }}"
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        id: deploy
        uses: decentraland/dcl-deploy-action@main
        with:
          dockerImage: "${{ needs.quay-build-push.outputs.registry-path }}"
          serviceName: ${{ inputs.service-name }}
          env: ${{ inputs.deployment-environment }}
          token: ${{ secrets.GITHUB_TOKEN }}
